### ISSUE TITLE
Adding timestamp links (tags)

### ISSUE THREAD

**Issue by albfan** [asciinema/discussions#115]
Say I'm doing an asciicast about config a program. I want to add a tag at some timestamp to say:

1. screen for config file
2. screen for feature A
3. screen for feature B

So you can go directly to that points of screencast

Maybe this is related with asciinema/asciinema#128 (annotations) Is there any docs about that? How can I help to release this feature?

**Comment by bkil** [comment]
Related or duplicate: https://github.com/asciinema/discussions/issues/99
