### ISSUE TITLE
asciinema-player with React 

### ISSUE THREAD

**Issue by Ceditvodu** [asciinema/discussions#251]
Hello. 

Asciinema player has very strange behavior in my small React project. On static page with same parametrs it works perfetct both online and offline. On React it doesn't work properly. It shows on page, but when I click on play button it start endless loading. Also there is no any errors in console. 

Anybody know how to fix it? 

Thanks.

**Comment by ymolists** [comment]
Does anyone has an example that works with nextjs , react 18 and typescript please ?
