### ISSUE TITLE
WIndows

### ISSUE THREAD

**Issue by SR-Lut3t1um** [asciinema/discussions#67]
Now before you just close this issue, I do undertand why you did not want to support windows terminals. However the new [OFFICAL](https://github.com/microsoft/terminal) Terminal from windows is goint to have a proper PTY support. So implementing this in windows should be possible.

**Comment by rashil2000** [comment]
FWIW, as mentioned in https://github.com/asciinema/discussions/issues/48
there is a native C# port for Windows that records in the asciicast format and supports uploading directly to asciinema.org

@sickill would you mind adding this info to the readme? 

(or you can also use [terminalizer](https://github.com/faressoft/terminalizer) which is cross-platform and directly outputs GIFs)
